name: gallaryapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_offline: ^4.0.0
  hive: ^2.2.3
  hive_flutter: null
  intl: ^0.19.0
  path_provider: ^2.1.1
  connectivity_plus: ^6.0.4
  shared_preferences: ^2.3.1
  easy_localization: ^3.0.7



dev_dependencies:
  build_runner: null
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: null

flutter:
  uses-material-design: true
  assets:
    - translations/
    
flutter_intl:
  enabled: true